name: SonarQube Cloud Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    name: Analyze with SonarQube
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov psycopg2-binary
        
    - name: Run tests with coverage
      run: |
        python -m pytest test/test_models/ --cov=models --cov-report=xml --quiet
        echo "✅ Coverage report generated"
        
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=ggeraa
          -Dsonar.projectKey=GgeraA_PWS-PROJECT
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.sources=models
          -Dsonar.tests=test
          -Dsonar.exclusions=services/**,templates/**,static/**,config.py,app.py